"""Parity of weatherai.models.genfocal.flow against the official JAX outputs stored in tests/models/genfocal/data/ref_flow.npz
(generated by scripts/genfocal_make_ref.py from the unchanged swirl_dynamics code).  Writes docs/results/genfocal_parity.json."""
import json
import os

import numpy as np
import torch

from weatherai.models.genfocal import logistic_time_sampler, reflow_loss, sample_flow
from weatherai.models.genfocal.reference import TinyFlow

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def run(ref_path=os.path.join(ROOT, "tests", "models", "genfocal", "data", "ref_flow.npz")):
    d = np.load(ref_path)
    t = lambda k: torch.from_numpy(d[k])
    net = TinyFlow.from_ref(d).double()
    f64 = lambda k: t(k).double()
    cond = {"channel:mean": f64("cm"), "channel:std": f64("cs")}
    x0, x1, u = f64("x0"), f64("x1"), f64("u")
    res = {}
    for tag, uu in (("u", u), ("logi", logistic_time_sampler(u))):
        for wtag, w in (("", None), ("_w", f64("wn"))):
            k = f"loss_{tag}{wtag}"
            l = float(reflow_loss(net, x0, x1, cond, u=uu, weighted_norm=w).detach())
            res[k] = {"native": l, "official": float(d[k]), "rel": abs(l - float(d[k])) / abs(float(d[k]))}
    for n in (4, 8):
        for rev in (False, True):
            k = f"sample_n{n}_{'rev' if rev else 'fwd'}"
            y = sample_flow(net, x0, cond, num_steps=n, reverse=rev) * f64("os") + f64("om")
            ref = t(k).double()
            res[k] = {"rel_l2": float((y - ref).norm() / ref.norm()), "max_abs": float((y - ref).abs().max())}
    return res


if __name__ == "__main__":
    r = run()
    json.dump(r, open(os.path.join(ROOT, "docs", "results", "genfocal_parity.json"), "w"), indent=1)
    print(json.dumps(r, indent=1))
